#!/bin/bash
#SBATCH -A m2_jgu-paa			# Account
#SBATCH -J hashreadmappermake             # Job name
#SBATCH -o hashreadmapper.\%j.out     # Specify stdout output file where \% expands to jobID
#SBATCH -p m2_gpu-compile                # Queue name
#SBATCH -n 1                   # Total number of tasks (=cores)
#SBATCH -N 1                    # Number of sockets
#SBATCH -t 01:00:00             # Run time (hh_mm_ss) - 20 minutes
#SBATCH --mem-per-cpu=1800      # Memory per CPU (default is 1200 MB)

#SBATCH --mail-type=ALL
#SBATCH --mail-user=chsteiss@students.uni-mainz.de

module load lib/zlib/1.2.12

module load compiler/GCCcore/11.3.0
module load compiler/GCC/11.3.0
module load system/CUDAcore/11.3.0
module load system/CUDA/11.6.1


#
#module load lib/zlib/1.2.12
#module load compiler/GCCcore/12.2.0
#module load compiler/GCC/12.2.0
#module load system/CUDAcore/11.3.0
#m#odule load system/CUDA/11.8.0
#





#lscpu
nvcc-smi # --version
#echo "platzhalter"
srun make gpu
